services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    entrypoint:
    - sleep
    - infinity
    # image: docker/dev-environments-go:stable-1
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  oidc2middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      KEY_FILE: /secrets/op_private.key
    volumes:
      - ./.secrets:/secrets:ro

