services:
  # Internal Certificate Authority (Step-CA):
  ca:
    image: smallstep/step-ca:${STEP_CA_VERSION:-0.30.1} # Use Smallstep CA image from Docker Hub
    profiles:
      - test
      - dev
    restart: unless-stopped
    depends_on:
      - ca_db
    networks:
      # Network to reverse proxy for ACME TLS-ALPN-01 challenge:
      ca_proxy:
        ipv4_address: ${NETWORK_CA_PROXY_CA:-172.20.0.26}
      # Network to CA database:
      ca_db:
        ipv4_address: ${NETWORK_CA_DB_CA:-172.20.0.34}
    extra_hosts:
      - "${OP_HOST:-op.localhost}=${NETWORK_CA_PROXY_PROXY:-172.20.0.27}" # Map $OP_HOST to host gateway for ACME TLS-ALPN-01 challenge
      - "ca_db=${NETWORK_CA_DB_DB:-172.20.0.35}" # The database's hostname
    environment:
      # Database configuration:
      PGSSLMODE: disable
      PGHOST: ca_db
      PGPORT: 5432
      PGDATABASE: stepca
      PGUSER: stepca
      PGPASSFILE: /run/secrets/ca_db_passfile
    command: >
      step-ca /home/step/config/ca.json
      --password-file=/run/secrets/ca_intermediate_key_password
    secrets:
      - ca_intermediate_key_password # Intermediate CA private key password
      - ca_intermediate_key # Intermediate CA private key file
      - ca_intermediate_cert # Intermediate CA certificate file
      - ca_root_cert # Root CA certificate file
      - ca_db_passfile # Database password file
    volumes:
      - ./ca/authorities/:/home/step/authorities/:ro # The policy and settings files
      - ./.secrets/ca/db/:/home/step/db/:rw # The CA database for issued certificates
      - ./ca/config/ca.json:/home/step/config/ca.json:ro # The common configuration files and defaults
  # Internal Certificate Authority's database (PostgreSQL):
  ca_db:
    image: postgres:${KEYCLOAK_POSTGRES_VERSION:-18-alpine}
    profiles:
      - prod
      - test
      - dev
    restart: unless-stopped
    networks:
      # Network to Certificate Authority:
      ca_db:
        ipv4_address: ${NETWORK_CA_DB_DB:-172.20.0.35}
    environment:
      POSTGRES_DB: stepca # Database name
      POSTGRES_USER: stepca # Database username
      POSTGRES_PASSWORD_FILE: /run/secrets/ca_db_password # Database password secret file
    secrets:
      - ca_db_password # Database password
    volumes:
      - ca_db:/var/lib/postgresql # Mount PostgreSQL data to shared Docker Volume 'userdb'

  # Reverse Proxy (Traefik):
  proxy-prod:
    image: traefik:${TRAEFIK_VERSION:-v3.6}
    profiles:
      - prod
    restart: unless-stopped
    ports:
      - 80:80/tcp # HTTP
      - 443:443/tcp # HTTPS
      - 443:443/udp # HTTP/3
    networks:
      # Network for host port mapping
      proxy:
      # Network to OpenID Provider:
      proxy_op:
        ipv4_address: ${NETWORK_PROXY_OP_PROXY:-172.20.0.2}
      # Network to OIDC² middleware:
      proxy_oidc2middleware:
        ipv4_address: ${NETWORK_PROXY_OIDC2MIDDLEWARE_PROXY:-172.20.0.18}
    command:
      - "--accesslog=true"
      - "--log.level=ERROR"
      - "--entrypoints.web.address=:80/tcp" # HTTP entrypoint
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" # Permanently redirect HTTP to HTTPS
      - "--entrypoints.websecure.address=:443" # HTTPS entrypoint
      - "--entrypoints.websecure.http3=true" # Enable HTTP/3 on HTTPS entrypoint
      - "--entrypoints.websecure.http3.advertisedport=443" # Advertise port 443/udp for HTTP/3
      - "--entrypoints.websecure.http.tls=true" # Enable TLS on HTTPS entrypoint
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt" # Use Let's Encrypt for TLS certificate resolution
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true" # Use TLS-ALPN-01 challenge for certificate resolution
      - "--certificatesresolvers.letsencrypt.acme.profile=shortlived" # Use Let's Encrypt short lived certificate profile (160h lifetime)
      - "--certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json" # Store Let's Encrypt certificates in mounted volume
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}" # Email for Let's Encrypt registration
      - "--providers.docker=true" # Enable Docker provider
      - "--providers.docker.endpoint=unix:///var/run/docker.sock" # Path to docker socket to listen to new services
      - "--providers.docker.exposedbydefault=false" # Do not expose every service by default
      - "--providers.docker.network=proxy" # User 'proxy' network as default network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount host's docker socket for service discovery
      - ./.secrets/certs/:/certs/:rw # Mount local directory for Let's Encrypt certificate storage
  proxy-test:
    image: traefik:${TRAEFIK_VERSION:-v3.6}
    profiles:
      - test
      - dev
    restart: unless-stopped
    depends_on:
      - ca # Internal CA
    ports:
      - 80:80/tcp # HTTP
      - 443:443/tcp # HTTPS
      - 443:443/udp # HTTP/3
    networks:
      # Network for host port mapping
      proxy:
      # Network to reverse proxy for ACME TLS-ALPN-01 challenge:
      ca_proxy:
        ipv4_address: ${NETWORK_CA_PROXY_PROXY:-172.20.0.27}
      # Network to OpenID Provider:
      proxy_op:
        ipv4_address: ${NETWORK_PROXY_OP_PROXY:-172.20.0.2}
      # Network to OIDC² middleware:
      proxy_oidc2middleware:
        ipv4_address: ${NETWORK_PROXY_OIDC2MIDDLEWARE_PROXY:-172.20.0.18}
    extra_hosts:
      - "${CA_HOST:-ca.localhost}=${NETWORK_CA_PROXY_CA:-172.20.0.26}"
    command:
      - "--accesslog=true"
      - "--log.level=INFO"
      - "--entrypoints.web.address=:80/tcp" # HTTP entrypoint
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" # Permanently redirect HTTP to HTTPS
      - "--entrypoints.websecure.address=:443" # HTTPS entrypoint
      - "--entrypoints.websecure.http3=true" # Enable HTTP/3 on HTTPS entrypoint
      - "--entrypoints.websecure.http3.advertisedport=443" # Advertise port 443/udp for HTTP/3
      - "--entrypoints.websecure.http.tls=true" # Enable TLS on HTTPS entrypoint
      - "--entrypoints.websecure.http.tls.certresolver=stepca" # Use Let's Encrypt for TLS certificate resolution
      - "--certificatesresolvers.stepca.acme.tlschallenge=true" # Use TLS-ALPN-01 challenge for certificate resolution
      - "--certificatesresolvers.stepca.acme.caServer=https://${CA_HOST:-ca.localhost}/acme/internal/directory" # Use internal CA for ACME certificate resolution
      - "--certificatesresolvers.stepca.acme.caCertificates=/run/secrets/ca_root_cert" # Root certificate of the internal CA to validate ACME challenges
      - "--certificatesresolvers.stepca.acme.caServerName=${CA_HOST:-ca.localhost}" # The internal CA's expected hostname
      - "--certificatesresolvers.stepca.acme.storage=/certs/acme.json" # Store Step-CA certificates in mounted volume
      - "--certificatesresolvers.stepca.acme.email=${ACME_EMAIL:-admin@example.com}" # Email for Let's Encrypt registration
      - "--providers.docker=true" # Enable Docker provider
      - "--providers.docker.endpoint=unix:///var/run/docker.sock" # Path to docker socket to listen to new services
      - "--providers.docker.exposedbydefault=false" # Do not expose every service by default
      - "--providers.docker.network=proxy" # User 'proxy' network as default network
    secrets:
      - ca_root_cert # Root certificate of the internal CA to validate ACME challenges
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount host's docker socket for service discovery
      - ./.secrets/certs/:/certs/:rw # Mount local directory for Let's Encrypt certificate storage

  # OpenID Provider (Keycloak):
  op-prod:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-26.5.6}
    profiles:
      - prod
    restart: unless-stopped
    depends_on:
      - proxy-prod
      - op_db
    networks:
      # Network to reverse proxy:
      proxy_op:
        ipv4_address: ${NETWORK_PROXY_OP_OP:-172.20.0.3}
      # Network to database:
      op_db:
        ipv4_address: ${NETWORK_OP_DB_OP:-172.20.0.10}
    labels:
      - traefik.enable=true
      - traefik.http.routers.op.entrypoints=websecure
      - traefik.http.routers.op.rule=Host(`${OP_HOST:-op.example.com}`)
      - traefik.http.routers.op.priority=1
      - traefik.http.routers.op.service=op
      - traefik.http.services.op.loadbalancer.server.url=http://${NETWORK_PROXY_OP_OP:-172.20.0.3}:8080
    environment:
      # Database configuration:
      KC_DB: postgres # Use a PostgreSQL database
      KC_DB_URL: jdbc:postgresql://${NETWORK_OP_DB_DB:-172.20.0.11}:5432/keycloak # PostgreSQL database connection string
      KC_DB_USERNAME: keycloak # Database username
      # Hosting configuration:
      KC_HOSTNAME: ${OP_HOST:-op.example.com} # Proxied hostname
      KC_PROXY_HEADERS: xforwarded # Expect X-Forwarded-* headers from reverse proxy
      # Admin configuration:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
    env_file:
      - ./.secrets/op.env # Load admin's initial username and password from generated environment file
    command:
      - "start" # Start in production mode
      - "--optimized" # Load optimized defaults
      - "--import-realm" # Import realm configuration
    volumes:
      - ./keycloak/realms/:/opt/keycloak/data/import/:ro # Default realm configuration to import
  op-test:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-26.5.6}
    profiles:
      - test
      - dev
    restart: unless-stopped
    depends_on:
      - proxy-test
      - op_db
    networks:
      # Network to reverse proxy:
      proxy_op:
        ipv4_address: ${NETWORK_PROXY_OP_OP:-172.20.0.3}
      # Network to database:
      op_db:
        ipv4_address: ${NETWORK_OP_DB_OP:-172.20.0.10}
    labels:
      - traefik.enable=true
      - traefik.http.routers.op.entrypoints=websecure
      - traefik.http.routers.op.rule=Host(`${OP_HOST:-op.localhost}`)
      - traefik.http.routers.op.priority=1
      - traefik.http.routers.op.service=op
      - traefik.http.services.op.loadbalancer.server.url=http://${NETWORK_PROXY_OP_OP:-172.20.0.3}:8080
    environment:
      # Database configuration:
      KC_DB: postgres # Use a PostgreSQL database
      KC_DB_URL: jdbc:postgresql://${NETWORK_OP_DB_DB:-172.20.0.11}:5432/keycloak # PostgreSQL database connection string
      KC_DB_USERNAME: keycloak # Database username
      # Hosting configuration:
      KC_HOSTNAME: ${OP_HOST:-op.localhost} # Proxied hostname
      KC_PROXY_HEADERS: xforwarded # Expect X-Forwarded-* headers from reverse proxy
      # Admin configuration:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
    env_file:
      - ./.secrets/op.env # Load admin's initial username and password from generated environment file
    command:
      - "start-dev" # Start in development mode
      - "--import-realm" # Import realm configuration
    volumes:
      - ./keycloak/realms/:/opt/keycloak/data/import/:ro # Default realm configuration to import
  # Keycloak Database (PostgreSQL):
  op_db:
    image: postgres:${KEYCLOAK_POSTGRES_VERSION:-18-alpine}
    profiles:
      - prod
      - test
      - dev
    restart: unless-stopped
    networks:
      # Network to OpenID Provider:
      op_db:
        ipv4_address: ${NETWORK_OP_DB_DB:-172.20.0.11}
    environment:
      POSTGRES_DB: keycloak # Database name
      POSTGRES_USER: keycloak # Database username
      POSTGRES_PASSWORD_FILE: /run/secrets/op_db_password # Database password secret file
    secrets:
      - op_db_password # Database password
    volumes:
      - op_db:/var/lib/postgresql # Mount PostgreSQL data to shared Docker Volume 'userdb'

  # OIDC² Middleware (this application):
  oidc2middleware-prod:
    image: jonasprimbs/oidc-e2ea-server:${OIDC2MIDDLEWARE_VERSION:-0.2}
    profiles:
      - prod
    restart: unless-stopped
    depends_on:
      - proxy-prod
      - op-prod
    networks:
      # Network to reverse proxy:
      proxy_oidc2middleware:
        ipv4_address: ${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}
    extra_hosts:
      - "${OP_HOST:-op.example.com}=${NETWORK_PROXY_OIDC2MIDDLEWARE_PROXY:-172.20.0.18}" # Send OP traffic to reverse proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.oidc2middleware.entrypoints=websecure
      - traefik.http.routers.oidc2middleware.priority=2
      - traefik.http.routers.oidc2middleware.rule=!ClientIP(`${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}`) && Host(`${OP_HOST:-op.localhost}`) && Path(`/realms/${KEYCLOAK_REALM:-oidc2}/protocol/openid-connect/token`) # Redirect token request to OIDC² middleware for external requests only
      - traefik.http.routers.oidc2middleware.middlewares=oidc2middleware_pathstrip,oidc2middleware_cors
      - traefik.http.middlewares.oidc2middleware_pathstrip.stripprefix.prefixes=/realms/${KEYCLOAK_REALM:-oidc2}/protocol/openid-connect/token
      - traefik.http.middlewares.oidc2middleware_cors.headers.customResponseHeaders.Access-Control-Allow-Origin=${CORS_ALLOWED_ORIGINS:-https://editor.swagger.io}
      - traefik.http.routers.oidc2middleware.service=oidc2middleware
      - traefik.http.services.oidc2middleware.loadbalancer.server.url=http://${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}:8080
    environment:
      KEY_FILE: /run/secrets/op_private_key # Private ICT signing key
      KEY_ID: ${KEY_ID} # Key ID of the ICT signing key
      ISSUER: https://${OP_HOST:-op.example.com}/realms/${KEYCLOAK_REALM:-oidc2} # Issuer of the ICT
      ALG: ${ALG:-RS256} # ICT signing algorithm
      TOKEN_PERIOD: ${TOKEN_PERIOD:-3600} # Lifetime of the ICT
      PORT: 8080
    secrets:
      - op_private_key # Private ICT signing key file
  oidc2middleware-test:
    image: jonasprimbs/oidc-e2ea-server:${OIDC2MIDDLEWARE_VERSION:-0.2}
    profiles:
      - test
    restart: unless-stopped
    depends_on:
      - proxy-test
      - op-test
    networks:
      # Network to reverse proxy:
      proxy_oidc2middleware:
        ipv4_address: ${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}
    extra_hosts:
      - "${OP_HOST:-op.localhost}=${NETWORK_PROXY_OIDC2MIDDLEWARE_PROXY:-172.20.0.18}" # Send OP traffic to reverse proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.oidc2middleware.entrypoints=websecure
      - traefik.http.routers.oidc2middleware.priority=2
      - traefik.http.routers.oidc2middleware.rule=!ClientIP(`${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}`) && Host(`${OP_HOST:-op.localhost}`) && Path(`/realms/${KEYCLOAK_REALM:-oidc2}/protocol/openid-connect/token`) # Redirect token request to OIDC² middleware for external requests only
      - traefik.http.routers.oidc2middleware.middlewares=oidc2middleware_pathstrip,oidc2middleware_cors
      - traefik.http.middlewares.oidc2middleware_pathstrip.stripprefix.prefixes=/realms/${KEYCLOAK_REALM:-oidc2}/protocol/openid-connect/token
      - traefik.http.middlewares.oidc2middleware_cors.headers.customResponseHeaders.Access-Control-Allow-Origin=${CORS_ALLOWED_ORIGINS:-https://editor.swagger.io}
      - traefik.http.routers.oidc2middleware.service=oidc2middleware
      - traefik.http.services.oidc2middleware.loadbalancer.server.url=http://${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}:8080
    environment:
      KEY_FILE: /run/secrets/op_private_key # Private ICT signing key
      KEY_ID: ${KEY_ID} # Key ID of the ICT signing key
      ISSUER: https://${OP_HOST:-op.localhost}/realms/${KEYCLOAK_REALM:-oidc2} # Issuer of the ICT
      ALG: ${ALG:-RS256} # ICT signing algorithm
      TOKEN_PERIOD: ${TOKEN_PERIOD:-3600} # Lifetime of the ICT
      PORT: 8080
    secrets:
      - op_private_key # Private ICT signing key file
    volumes:
      - ./.secrets/ca_root.crt:/etc/ssl/certs/ca-certificates.crt:ro # Trust internal CA
  oidc2middleware-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    profiles:
      - dev
    restart: unless-stopped
    depends_on:
      - proxy-test
      - op-test
    networks:
      # Network to reverse proxy:
      proxy_oidc2middleware:
        ipv4_address: ${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}
    extra_hosts:
      - "${OP_HOST:-op.localhost}=${NETWORK_PROXY_OIDC2MIDDLEWARE_PROXY:-172.20.0.18}" # Send OP traffic to reverse proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.oidc2middleware.entrypoints=websecure
      - traefik.http.routers.oidc2middleware.priority=2
      - traefik.http.routers.oidc2middleware.rule=!ClientIP(`${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}`) && Host(`${OP_HOST:-op.localhost}`) && Path(`/realms/${KEYCLOAK_REALM:-oidc2}/protocol/openid-connect/token`) # Redirect token request to OIDC² middleware for external requests only
      - traefik.http.routers.oidc2middleware.middlewares=oidc2middleware_pathstrip,oidc2middleware_cors
      - traefik.http.middlewares.oidc2middleware_pathstrip.stripprefix.prefixes=/realms/${KEYCLOAK_REALM:-oidc2}/protocol/openid-connect/token
      - traefik.http.middlewares.oidc2middleware_cors.headers.customResponseHeaders.Access-Control-Allow-Origin=${CORS_ALLOWED_ORIGINS:-https://editor.swagger.io}
      - traefik.http.routers.oidc2middleware.service=oidc2middleware
      - traefik.http.services.oidc2middleware.loadbalancer.server.url=http://${NETWORK_PROXY_OIDC2MIDDLEWARE_OIDC2MIDDLEWARE:-172.20.0.19}:8080
    environment:
      KEY_FILE: /run/secrets/op_private_key # Private ICT signing key
      KEY_ID: ${KEY_ID} # Key ID of the ICT signing key
      ISSUER: https://${OP_HOST:-op.localhost}/realms/${KEYCLOAK_REALM:-oidc2} # Issuer of the ICT
      ALG: ${ALG:-RS256} # ICT signing algorithm
      TOKEN_PERIOD: ${TOKEN_PERIOD:-3600} # Lifetime of the ICT
      PORT: 8080
    secrets:
      - op_private_key # Private ICT signing key file
    volumes:
      - ./.secrets/ca_root.crt:/etc/ssl/certs/ca-certificates.crt:ro # Trust internal CA

networks:
  # Network for host port mapping
  proxy:
    driver: bridge
  # Network between reverse proxy and OpenID Provider:
  proxy_op:
    driver: bridge
    internal: true # No internet access
    ipam:
      config:
        - subnet: ${NETWORK_PROXY_OP_CIDR:-172.20.0.0/29}
          gateway: ${NETWORK_PROXY_OP_GATEWAY:-172.20.0.1}
  # Network between OpenID Provider and its database:
  op_db:
    driver: bridge
    internal: true # No internet access
    ipam:
      config:
        - subnet: ${NETWORK_OP_DB_CIDR:-172.20.0.8/29}
          gateway: ${NETWORK_OP_DB_GATEWAY:-172.20.0.9}
  # Network between reverse proxy and OIDC² middleware:
  proxy_oidc2middleware:
    driver: bridge
    internal: true # No internet access
    ipam:
      config:
        - subnet: ${NETWORK_PROXY_OIDC2MIDDLEWARE_CIDR:-172.20.0.16/29}
          gateway: ${NETWORK_PROXY_OIDC2MIDDLEWARE_GATEWAY:-172.20.0.17}
  # Network between internal certificate authority and reverse proxy for ACME TLS-ALPN-01 challenge:
  ca_proxy:
    driver: bridge
    internal: true # No internet access
    ipam:
      config:
        - subnet: ${NETWORK_CA_PROXY_CIDR:-172.20.0.24/29}
          gateway: ${NETWORK_CA_PROXY_GATEWAY:-172.20.0.25}
  # Network between internal certificate authority and its database:
  ca_db:
    driver: bridge
    internal: true # No internet access
    ipam:
      config:
        - subnet: ${NETWORK_CA_DB_CIDR:-172.20.0.32/29}
          gateway: ${NETWORK_CA_DB_GATEWAY:-172.20.0.33}

secrets:
  # Internal certificate's secrets:
  ca_intermediate_key_password: # Internal intermediate CA's private key password
    file: ./.secrets/ca_intermediate_password.txt
  ca_intermediate_key: # Internal intermediate CA's private key
    file: ./.secrets/ca_intermediate.key
  ca_intermediate_cert: # Internal intermediate CA's certificate
    file: ./.secrets/ca_intermediate.crt
  ca_root_cert: # External root CA's certificate
    file: ./.secrets/ca_root.crt
  ca_db_passfile: # Internal Certificate Authority's database password file
    file: ./.secrets/ca_db_passfile.txt

  # OpenID Provider's database secrets:
  op_db_password: # OpenID Provider database password
    file: ./.secrets/op_db_password.txt
  # OpenID Provider's ICT secrets:
  op_private_key: # OpenID Provider ICT signing private key file
    file: ./.secrets/op_private.pem

  # Certificate Autority's database secrets:
  ca_db_password: # Certificate Authority database password
    file: ./.secrets/ca_db_password.txt

volumes:
  op_db: # OpenID Provider's persistent database
  ca_db: # Certificate Autority's persistent database
