/*
 * OIDC RIDT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's Remote ID Token endpoint for userinfo.
 *
 * API version: 0.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ridt

type EcSigningAlgorithm string

// List of EcSigningAlgorithms
const (
	ES256 EcSigningAlgorithm = "ES256"
	ES384 EcSigningAlgorithm = "ES384"
	ES512 EcSigningAlgorithm = "ES512"
)
