/*
 * OIDC RIDT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's Remote ID Token endpoint for userinfo.
 *
 * API version: 0.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ridt

type IatResponse struct {
	RemoteIdToken string `json:"remote_id_token"`
	// Number of seconds until the Remote ID Token expires.
	ExpiresIn int32 `json:"expires_in,omitempty"`
	// Space delimited claims provided in the Remote ID Token.
	Claims string `json:"claims,omitempty"`
}
