/*
 * OIDC RIDT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's Remote ID Token endpoint for userinfo.
 *
 * API version: 0.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ridt

type RsaSigningAlgorithm string

// List of RsaSigningAlgorithms
const (
	RS256 RsaSigningAlgorithm = "RS256"
	RS384 RsaSigningAlgorithm = "RS384"
	RS512 RsaSigningAlgorithm = "RS512"
)
