/*
 * OIDC IAT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Assertion Token endpoint for userinfo.
 *
 * API version: 0.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iat

type KeyType string

// List of KeyTypes
const (
	EC  KeyType = "EC"
	RSA KeyType = "RSA"
)

func KeyTypeFromString(value string) (KeyType, bool) {
	switch value {
	case "EC":
		return EC, true
	case "RSA":
		return RSA, true
	default:
		return "", false
	}
}
