/*
 * OIDC IAT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Assertion Token endpoint for userinfo.
 *
 * API version: 0.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package iat

// Information about ocurred error.
type ErrorStatus struct {
	// Status Code
	Code int `json:"code"`
	// Status Text
	Status string `json:"status"`
	// More detailed description
	Description string `json:"description,omitempty"`
}
